version: "3.8"

services:
    db:
        container_name: db
        image: postgres:alpine
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data/
        env_file:
            - .env
    backend:
        container_name: backend
        restart: always
        build:
            dockerfile: ./Dockerfile.dev
        working_dir: /src/backend/
        command: ["python3","manage.py","runserver","0.0.0.0:8000"]
        env_file:
            - .env
        volumes:
            - ./backend/:/src/backend/
            - ./storage/:/src/storage/
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    db_data:
